# Generated by Django 2.0.9 on 2018-11-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='percentual',
            field=models.IntegerField(default=0),
        ),
    ]
