# Generated by Django 2.0.9 on 2018-11-21 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0005_choice_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_date',
            field=models.DateField(default='9999-12-31', verbose_name=datetime.datetime(2018, 11, 21, 18, 22, 58, 859996)),
        ),
    ]
