# Generated by Django 2.0.9 on 2018-11-21 18:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0007_auto_20181121_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voto', to='pools.Choice'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_date',
            field=models.DateField(default='9999-12-31', verbose_name=datetime.datetime(2018, 11, 21, 18, 35, 2, 961259)),
        ),
    ]
