# Generated by Django 2.0.9 on 2018-11-21 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0008_auto_20181121_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='votes',
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_date',
            field=models.DateField(default='9999-12-31', verbose_name=datetime.datetime(2018, 11, 21, 18, 38, 16, 397750)),
        ),
    ]
