# Generated by Django 2.0.9 on 2018-11-21 18:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0014_auto_20181121_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_date',
            field=models.DateField(verbose_name=datetime.datetime(2018, 11, 21, 18, 51, 29, 930400, tzinfo=utc)),
        ),
    ]
