# Generated by Django 2.0.9 on 2018-11-21 18:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0015_auto_20181121_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voto', to='pools.Choice'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 11, 21, 18, 52, 39, 802428, tzinfo=utc)),
        ),
    ]
