# Generated by Django 2.0.9 on 2018-11-21 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0004_auto_20181121_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice',
            field=models.DateField(default='9999-12-31', verbose_name=datetime.datetime(2018, 11, 21, 18, 21, 16, 68743)),
        ),
    ]
