# Generated by Django 2.0.9 on 2018-11-21 18:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0006_auto_20181121_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_date', models.DateField(default='9999-12-31', verbose_name=datetime.datetime(2018, 11, 21, 18, 32, 49, 226416))),
                ('votes', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_date',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='vote',
            name='choice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voto', to='pools.Choice'),
        ),
    ]
