# Generated by Django 2.0.9 on 2018-11-21 18:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0016_auto_20181121_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voto', to='pools.Choice'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
